### PR TITLE
Implementation of the Restic engine

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Comment by mcanevet** [comment]
Great work!
@raphink I think this can not break other engines so I suppose we can safely merge this, right?

**Comment by mcanevet** [comment]
@raphink the CI is also broken on master...

**Comment by raphink** [comment]
@mcanevet for other reasons though. It's a missing dependency here it seems.

**Comment by cryptobioz** [comment]
We can fix the problem with dependencies by using Go 1.9.

**Pull request merged**
