### PR TITLE
Add ssh-options to duplicity container (Fixes #32)

### LINKED ISSUE #32: Add --ssh-options="-oStrictHostKeyChecking=no" to duplicity parameters

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by mcanevet** [comment]
@raphink any clue why Travis is not happy?

**Comment by raphink** [comment]
@mcanevet Godeps stuff

**Comment by mcanevet** [comment]
@raphink how can I fix this?

**Comment by raphink** [comment]
Run `godeps save` and make sure all of `_workspace` is commited.

**Comment by mcanevet** [comment]
@raphink still does not work...

**Pull request merged**
